export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_ADDITIONAL_TODAY_WEATHER = 'FETCH_ADDITIONAL_TODAY_WEATHER';
export const RECOMMENDED_MENUS = 'RECOMMENDED_MENUS';
export const REFRESH_MENU = 'REFRESH_MENU';
export const REFRESH_BUTTON = 'REFRESH_BUTTON';
